name: items
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  flutter_svg: ^2.0.4
  retrofit: ^4.0.1
  json_annotation: ^4.8.0
  dio: ^5.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  either_dart: ^0.3.0
  equatable: ^2.0.5
  stream_transform: ^2.1.0
  web_socket_channel: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  retrofit_generator: 6.0.0+1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter-Thin.ttf

flutter_gen:
  output: lib/generated_assets/
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
